/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol

// Source: src/sanity/schema.json
export type SanityImageAssetReference = {
	_ref: string
	_type: 'reference'
	_weak?: boolean
	[internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
}

export type CardImage = {
	asset?: SanityImageAssetReference
	media?: unknown // Unable to locate the referenced type "image.media" in schema
	hotspot?: SanityImageHotspot
	crop?: SanityImageCrop
	_type: 'image'
}

export type ResponsiveImage = {
	asset?: SanityImageAssetReference
	media?: unknown // Unable to locate the referenced type "responsive.image.media" in schema
	hotspot?: SanityImageHotspot
	crop?: SanityImageCrop
	_type: 'image'
}

export type TestimonialReference = {
	_ref: string
	_type: 'reference'
	_weak?: boolean
	[internalGroqTypeReferenceTo]?: 'testimonial'
}

export type TestimonialList = {
	_type: 'testimonial-list'
	pretitle?: string
	intro?: Array<{
		children?: Array<{
			marks?: Array<string>
			text?: string
			_type: 'span'
			_key: string
		}>
		style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
		listItem?: 'bullet' | 'number'
		markDefs?: Array<{
			href?: string
			_type: 'link'
			_key: string
		}>
		level?: number
		_type: 'block'
		_key: string
	}>
	testimonials?: Array<
		{
			_key: string
		} & TestimonialReference
	>
	layout?: 'grid' | 'carousel'
	layoutMobile?: 'grid' | 'carousel'
}

export type TestimonialFeatured = {
	_type: 'testimonial.featured'
	testimonial?: TestimonialReference
}

export type TabbedContent = {
	_type: 'tabbed-content'
	pretitle?: string
	intro?: Array<{
		children?: Array<{
			marks?: Array<string>
			text?: string
			_type: 'span'
			_key: string
		}>
		style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
		listItem?: 'bullet' | 'number'
		markDefs?: Array<{
			href?: string
			_type: 'link'
			_key: string
		}>
		level?: number
		_type: 'block'
		_key: string
	}>
	tabs?: Array<{
		label?: string
		pretitle?: string
		content?: Array<{
			children?: Array<{
				marks?: Array<string>
				text?: string
				_type: 'span'
				_key: string
			}>
			style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
			listItem?: 'bullet' | 'number'
			markDefs?: Array<{
				href?: string
				_type: 'link'
				_key: string
			}>
			level?: number
			_type: 'block'
			_key: string
		}>
		ctas?: Array<
			{
				_key: string
			} & Cta
		>
		assets?: Array<
			| ({
					_key: string
			  } & Img)
			| ({
					_key: string
			  } & Code)
			| ({
					_key: string
			  } & CustomHtml)
		>
		assetOnRight?: boolean
		assetBelowContent?: boolean
		_type: 'tab'
		_key: string
	}>
}

export type StepList = {
	_type: 'step-list'
	pretitle?: string
	intro?: Array<{
		children?: Array<{
			marks?: Array<string>
			text?: string
			_type: 'span'
			_key: string
		}>
		style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
		listItem?: 'bullet' | 'number'
		markDefs?: Array<{
			href?: string
			_type: 'link'
			_key: string
		}>
		level?: number
		_type: 'block'
		_key: string
	}>
	steps?: Array<{
		content?: Array<{
			children?: Array<{
				marks?: Array<string>
				text?: string
				_type: 'span'
				_key: string
			}>
			style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
			listItem?: 'bullet' | 'number'
			markDefs?: Array<{
				href?: string
				_type: 'link'
				_key: string
			}>
			level?: number
			_type: 'block'
			_key: string
		}>
		_type: 'step'
		_key: string
	}>
}

export type StatList = {
	_type: 'stat-list'
	pretitle?: string
	intro?: Array<{
		children?: Array<{
			marks?: Array<string>
			text?: string
			_type: 'span'
			_key: string
		}>
		style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
		listItem?: 'bullet' | 'number'
		markDefs?: Array<{
			href?: string
			_type: 'link'
			_key: string
		}>
		level?: number
		_type: 'block'
		_key: string
	}>
	stats?: Array<{
		prefix?: string
		value?: string
		suffix?: string
		text?: string
		_type: 'stat'
		_key: string
	}>
	textAlign?: string
}

export type SearchModule = {
	_type: 'search-module'
	pretitle?: string
	intro?: Array<{
		children?: Array<{
			marks?: Array<string>
			text?: string
			_type: 'span'
			_key: string
		}>
		style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
		listItem?: 'bullet' | 'number'
		markDefs?: Array<{
			href?: string
			_type: 'link'
			_key: string
		}>
		level?: number
		_type: 'block'
		_key: string
	}>
	ctas?: Array<
		{
			_key: string
		} & Cta
	>
	scope?: 'all' | 'pages' | 'path' | 'blog posts'
	path?: string
}

export type ScheduleModule = {
	_type: 'schedule-module'
	start?: string
	end?: string
	modules?: Array<
		| ({
				_key: string
		  } & Callout)
		| ({
				_key: string
		  } & CustomHtml)
		| ({
				_key: string
		  } & Hero)
		| ({
				_key: string
		  } & HeroSaas)
		| ({
				_key: string
		  } & HeroSplit)
		| ({
				_key: string
		  } & TestimonialFeatured)
	>
}

export type RichtextModule = {
	_type: 'richtext-module'
	options?: ModuleOptions
	content?: Array<
		| {
				children?: Array<{
					marks?: Array<string>
					text?: string
					_type: 'span'
					_key: string
				}>
				style?:
					'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
				listItem?: 'bullet' | 'number'
				markDefs?: Array<{
					href?: string
					_type: 'link'
					_key: string
				}>
				level?: number
				_type: 'block'
				_key: string
		  }
		| {
				asset?: SanityImageAssetReference
				media?: unknown
				hotspot?: SanityImageHotspot
				crop?: SanityImageCrop
				alt?: string
				loading?: 'lazy' | 'eager'
				caption?: string
				source?: string
				_type: 'image'
				_key: string
		  }
		| {
				tone?: 'note' | 'important' | 'tip' | 'warning' | 'caution'
				title?: string
				content?: Array<{
					children?: Array<{
						marks?: Array<string>
						text?: string
						_type: 'span'
						_key: string
					}>
					style?:
						'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
					listItem?: 'bullet' | 'number'
					markDefs?: Array<{
						href?: string
						_type: 'link'
						_key: string
					}>
					level?: number
					_type: 'block'
					_key: string
				}>
				_type: 'admonition'
				_key: string
		  }
		| ({
				_key: string
		  } & Code)
		| ({
				_key: string
		  } & CustomHtml)
	>
	stretch?: boolean
}

export type PricingReference = {
	_ref: string
	_type: 'reference'
	_weak?: boolean
	[internalGroqTypeReferenceTo]?: 'pricing'
}

export type PricingList = {
	_type: 'pricing-list'
	options?: ModuleOptions
	pretitle?: string
	intro?: Array<{
		children?: Array<{
			marks?: Array<string>
			text?: string
			_type: 'span'
			_key: string
		}>
		style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
		listItem?: 'bullet' | 'number'
		markDefs?: Array<{
			href?: string
			_type: 'link'
			_key: string
		}>
		level?: number
		_type: 'block'
		_key: string
	}>
	tiers?: Array<
		{
			_key: string
		} & PricingReference
	>
}

export type PersonReference = {
	_ref: string
	_type: 'reference'
	_weak?: boolean
	[internalGroqTypeReferenceTo]?: 'person'
}

export type PersonList = {
	_type: 'person-list'
	pretitle?: string
	intro?: Array<{
		children?: Array<{
			marks?: Array<string>
			text?: string
			_type: 'span'
			_key: string
		}>
		style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
		listItem?: 'bullet' | 'number'
		markDefs?: Array<{
			href?: string
			_type: 'link'
			_key: string
		}>
		level?: number
		_type: 'block'
		_key: string
	}>
	people?: Array<
		{
			_key: string
		} & PersonReference
	>
	layout?: 'grid' | 'carousel'
}

export type LogoReference = {
	_ref: string
	_type: 'reference'
	_weak?: boolean
	[internalGroqTypeReferenceTo]?: 'logo'
}

export type LogoList = {
	_type: 'logo-list'
	pretitle?: string
	intro?: Array<{
		children?: Array<{
			marks?: Array<string>
			text?: string
			_type: 'span'
			_key: string
		}>
		style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
		listItem?: 'bullet' | 'number'
		markDefs?: Array<{
			href?: string
			_type: 'link'
			_key: string
		}>
		level?: number
		_type: 'block'
		_key: string
	}>
	logos?: Array<
		{
			_key: string
		} & LogoReference
	>
	logoType?: 'default' | 'light' | 'dark'
	autoScroll?: boolean
	duration?: number
}

export type ReputationReference = {
	_ref: string
	_type: 'reference'
	_weak?: boolean
	[internalGroqTypeReferenceTo]?: 'reputation'
}

export type HeroSplit = {
	_type: 'hero.split'
	pretitle?: string
	content?: Array<
		| {
				children?: Array<{
					marks?: Array<string>
					text?: string
					_type: 'span'
					_key: string
				}>
				style?:
					'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
				listItem?: 'bullet' | 'number'
				markDefs?: Array<{
					href?: string
					_type: 'link'
					_key: string
				}>
				level?: number
				_type: 'block'
				_key: string
		  }
		| ({
				_key: string
		  } & CustomHtml)
		| {
				reputation?: ReputationReference
				_type: 'reputation-block'
				_key: string
		  }
	>
	ctas?: Array<
		{
			_key: string
		} & Cta
	>
	assets?: Array<
		| ({
				_key: string
		  } & Img)
		| ({
				_key: string
		  } & Code)
		| ({
				_key: string
		  } & CustomHtml)
	>
	assetOnRight?: boolean
	assetBelowContent?: boolean
}

export type HeroSaas = {
	_type: 'hero.saas'
	options?: ModuleOptions
	pretitle?: string
	content?: Array<
		| {
				children?: Array<{
					marks?: Array<string>
					text?: string
					_type: 'span'
					_key: string
				}>
				style?:
					'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
				listItem?: 'bullet' | 'number'
				markDefs?: Array<{
					href?: string
					_type: 'link'
					_key: string
				}>
				level?: number
				_type: 'block'
				_key: string
		  }
		| ({
				_key: string
		  } & Code)
		| ({
				_key: string
		  } & CustomHtml)
		| {
				reputation?: ReputationReference
				_type: 'reputation-block'
				_key: string
		  }
	>
	ctas?: Array<
		{
			_key: string
		} & Cta
	>
	assets?: Array<
		{
			_key: string
		} & Img
	>
	assetFaded?: boolean
}

export type Hero = {
	_type: 'hero'
	options?: ModuleOptions
	pretitle?: string
	content?: Array<
		| {
				children?: Array<{
					marks?: Array<string>
					text?: string
					_type: 'span'
					_key: string
				}>
				style?:
					'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
				listItem?: 'bullet' | 'number'
				markDefs?: Array<{
					href?: string
					_type: 'link'
					_key: string
				}>
				level?: number
				_type: 'block'
				_key: string
		  }
		| ({
				_key: string
		  } & CustomHtml)
		| {
				reputation?: ReputationReference
				_type: 'reputation-block'
				_key: string
		  }
	>
	ctas?: Array<
		{
			_key: string
		} & Cta
	>
	assets?: Array<
		{
			_key: string
		} & Img
	>
	alignItems?: string
	textAlign?: string
}

export type FlagList = {
	_type: 'flag-list'
	pretitle?: string
	intro?: Array<{
		children?: Array<{
			marks?: Array<string>
			text?: string
			_type: 'span'
			_key: string
		}>
		style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
		listItem?: 'bullet' | 'number'
		markDefs?: Array<{
			href?: string
			_type: 'link'
			_key: string
		}>
		level?: number
		_type: 'block'
		_key: string
	}>
	items?: Array<{
		icon?: Icon
		content?: Array<{
			children?: Array<{
				marks?: Array<string>
				text?: string
				_type: 'span'
				_key: string
			}>
			style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
			listItem?: 'bullet' | 'number'
			markDefs?: Array<{
				href?: string
				_type: 'link'
				_key: string
			}>
			level?: number
			_type: 'block'
			_key: string
		}>
		_type: 'flag'
		_key: string
	}>
	iconPosition?: 'top' | 'left'
}

export type CustomHtml = {
	_type: 'custom-html'
	options?: ModuleOptions
	className?: string
	html?: Code
	css?: Code
}

export type CreativeModule = {
	_type: 'creative-module'
	options?: ModuleOptions
	intro?: Array<{
		children?: Array<{
			marks?: Array<string>
			text?: string
			_type: 'span'
			_key: string
		}>
		style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
		listItem?: 'bullet' | 'number'
		markDefs?: Array<{
			href?: string
			_type: 'link'
			_key: string
		}>
		level?: number
		_type: 'block'
		_key: string
	}>
	modules?: Array<{
		subModules?: Array<
			| {
					asset?: SanityImageAssetReference
					media?: unknown
					hotspot?: SanityImageHotspot
					crop?: SanityImageCrop
					alt?: string
					aspectRatio?: string
					_type: 'image'
					_key: string
			  }
			| ({
					_key: string
			  } & Icon)
			| {
					pretitle?: string
					content?: Array<{
						children?: Array<{
							marks?: Array<string>
							text?: string
							_type: 'span'
							_key: string
						}>
						style?:
							'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
						listItem?: 'bullet' | 'number'
						markDefs?: Array<{
							href?: string
							_type: 'link'
							_key: string
						}>
						level?: number
						_type: 'block'
						_key: string
					}>
					_type: 'richtext'
					_key: string
			  }
			| {
					ctas?: Array<
						{
							_key: string
						} & Cta
					>
					_type: 'ctas'
					_key: string
			  }
			| ({
					_key: string
			  } & CustomHtml)
		>
		colSpan?: number
		_type: 'module'
		_key: string
	}>
	columns?: number
	visualSeparation?: boolean
	alignItems?: string
	textAlign?: string
}

export type CardList = {
	_type: 'card-list'
	options?: ModuleOptions
	pretitle?: string
	intro?: Array<{
		children?: Array<{
			marks?: Array<string>
			text?: string
			_type: 'span'
			_key: string
		}>
		style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
		listItem?: 'bullet' | 'number'
		markDefs?: Array<{
			href?: string
			_type: 'link'
			_key: string
		}>
		level?: number
		_type: 'block'
		_key: string
	}>
	ctas?: Array<
		{
			_key: string
		} & Cta
	>
	cards?: Array<{
		image?: CardImage
		content?: Array<{
			children?: Array<{
				marks?: Array<string>
				text?: string
				_type: 'span'
				_key: string
			}>
			style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
			listItem?: 'bullet' | 'number'
			markDefs?: Array<{
				href?: string
				_type: 'link'
				_key: string
			}>
			level?: number
			_type: 'block'
			_key: string
		}>
		ctas?: Array<
			{
				_key: string
			} & Cta
		>
		_type: 'card'
		_key: string
	}>
	layout?: 'grid' | 'carousel'
	columns?: number
	visualSeparation?: boolean
}

export type Callout = {
	_type: 'callout'
	content?: Array<
		| {
				children?: Array<{
					marks?: Array<string>
					text?: string
					_type: 'span'
					_key: string
				}>
				style?:
					'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
				listItem?: 'bullet' | 'number'
				markDefs?: Array<{
					href?: string
					_type: 'link'
					_key: string
				}>
				level?: number
				_type: 'block'
				_key: string
		  }
		| ({
				_key: string
		  } & Code)
		| {
				reputation?: ReputationReference
				_type: 'reputation-block'
				_key: string
		  }
	>
	ctas?: Array<
		{
			_key: string
		} & Cta
	>
}

export type Breadcrumbs = {
	_type: 'breadcrumbs'
	crumbs?: Array<
		{
			_key: string
		} & Link
	>
	hideCurrent?: boolean
}

export type BlogPostContent = {
	_type: 'blog-post-content'
	options?: ModuleOptions
}

export type BlogCategoryReference = {
	_ref: string
	_type: 'reference'
	_weak?: boolean
	[internalGroqTypeReferenceTo]?: 'blog.category'
}

export type BlogList = {
	_type: 'blog-list'
	options?: ModuleOptions
	pretitle?: string
	intro?: Array<{
		children?: Array<{
			marks?: Array<string>
			text?: string
			_type: 'span'
			_key: string
		}>
		style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
		listItem?: 'bullet' | 'number'
		markDefs?: Array<{
			href?: string
			_type: 'link'
			_key: string
		}>
		level?: number
		_type: 'block'
		_key: string
	}>
	layout?: 'grid' | 'carousel'
	showFeaturedPostsFirst?: boolean
	displayFilters?: boolean
	filterBySameCategory?: boolean
	limit?: number
	filteredCategory?: BlogCategoryReference
}

export type BlogFrontpage = {
	_type: 'blog-frontpage'
	mainPost?: 'recent' | 'featured'
	showFeaturedPostsFirst?: boolean
	itemsPerPage?: number
}

export type AccordionList = {
	_type: 'accordion-list'
	options?: ModuleOptions
	pretitle?: string
	intro?: Array<{
		children?: Array<{
			marks?: Array<string>
			text?: string
			_type: 'span'
			_key: string
		}>
		style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
		listItem?: 'bullet' | 'number'
		markDefs?: Array<{
			href?: string
			_type: 'link'
			_key: string
		}>
		level?: number
		_type: 'block'
		_key: string
	}>
	items?: Array<{
		summary?: string
		content?: Array<
			| {
					children?: Array<{
						marks?: Array<string>
						text?: string
						_type: 'span'
						_key: string
					}>
					style?:
						'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
					listItem?: 'bullet' | 'number'
					markDefs?: Array<{
						href?: string
						_type: 'link'
						_key: string
					}>
					level?: number
					_type: 'block'
					_key: string
			  }
			| {
					asset?: SanityImageAssetReference
					media?: unknown
					hotspot?: SanityImageHotspot
					crop?: SanityImageCrop
					alt?: string
					loading?: 'lazy' | 'eager'
					caption?: string
					source?: string
					_type: 'image'
					_key: string
			  }
			| ({
					_key: string
			  } & Code)
			| ({
					_key: string
			  } & CustomHtml)
		>
		open?: boolean
		_type: 'accordion'
		_key: string
	}>
	layout?: 'vertical' | 'horizontal'
	connect?: boolean
	generateSchema?: boolean
}

export type ModuleOptions = {
	_type: 'module-options'
	hidden?: boolean
	uid?: string
}

export type Metadata = {
	_type: 'metadata'
	title?: string
	description?: string
	slug?: Slug
	image?: {
		asset?: SanityImageAssetReference
		media?: unknown
		hotspot?: SanityImageHotspot
		crop?: SanityImageCrop
		_type: 'image'
	}
	noIndex?: boolean
}

export type LinkList = {
	_type: 'link.list'
	link?: Link
	links?: Array<
		{
			_key: string
		} & Link
	>
}

export type PageReference = {
	_ref: string
	_type: 'reference'
	_weak?: boolean
	[internalGroqTypeReferenceTo]?: 'page'
}

export type BlogPostReference = {
	_ref: string
	_type: 'reference'
	_weak?: boolean
	[internalGroqTypeReferenceTo]?: 'blog.post'
}

export type Link = {
	_type: 'link'
	label?: string
	type?: 'internal' | 'external'
	internal?: PageReference | BlogPostReference
	external?: string
	params?: string
}

export type Img = {
	_type: 'img'
	image?: {
		asset?: SanityImageAssetReference
		media?: unknown
		hotspot?: SanityImageHotspot
		crop?: SanityImageCrop
		_type: 'image'
	}
	responsive?: Array<{
		image?: ResponsiveImage
		media?: string
		_type: 'responsive'
		_key: string
	}>
	alt?: string
	loading?: 'lazy' | 'eager'
}

export type Icon = {
	_type: 'icon'
	image?: {
		asset?: SanityImageAssetReference
		media?: unknown
		hotspot?: SanityImageHotspot
		crop?: SanityImageCrop
		_type: 'image'
	}
	ic0n?: string
	size?: string
}

export type Cta = {
	_type: 'cta'
	link?: Link
	style?: 'action' | 'action-outline' | 'ghost' | 'link'
}

export type Testimonial = {
	_id: string
	_type: 'testimonial'
	_createdAt: string
	_updatedAt: string
	_rev: string
	content?: Array<{
		children?: Array<{
			marks?: Array<string>
			text?: string
			_type: 'span'
			_key: string
		}>
		style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
		listItem?: 'bullet' | 'number'
		markDefs?: Array<{
			href?: string
			_type: 'link'
			_key: string
		}>
		level?: number
		_type: 'block'
		_key: string
	}>
	source?: string
	author?: {
		name?: string
		title?: string
		image?: {
			asset?: SanityImageAssetReference
			media?: unknown
			hotspot?: SanityImageHotspot
			crop?: SanityImageCrop
			_type: 'image'
		}
	}
}

export type SanityImageCrop = {
	_type: 'sanity.imageCrop'
	top?: number
	bottom?: number
	left?: number
	right?: number
}

export type SanityImageHotspot = {
	_type: 'sanity.imageHotspot'
	x?: number
	y?: number
	height?: number
	width?: number
}

export type Pricing = {
	_id: string
	_type: 'pricing'
	_createdAt: string
	_updatedAt: string
	_rev: string
	title?: string
	highlight?: string
	price?: {
		base?: number
		strikethrough?: number
		suffix?: string
	}
	ctas?: Array<
		{
			_key: string
		} & Cta
	>
	content?: Array<{
		children?: Array<{
			marks?: Array<string>
			text?: string
			_type: 'span'
			_key: string
		}>
		style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
		listItem?: 'bullet' | 'number'
		markDefs?: Array<{
			href?: string
			_type: 'link'
			_key: string
		}>
		level?: number
		_type: 'block'
		_key: string
	}>
}

export type BookReference = {
	_ref: string
	_type: 'reference'
	_weak?: boolean
	[internalGroqTypeReferenceTo]?: 'book'
}

export type Person = {
	_id: string
	_type: 'person'
	_createdAt: string
	_updatedAt: string
	_rev: string
	name?: string
	slug?: Slug
	image?: {
		asset?: SanityImageAssetReference
		media?: unknown
		hotspot?: SanityImageHotspot
		crop?: SanityImageCrop
		_type: 'image'
	}
	title?: string
	tagline?: string
	location?: string
	company?: string
	socials?: Array<
		{
			_key: string
		} & Link
	>
	bio?: Array<{
		children?: Array<{
			marks?: Array<string>
			text?: string
			_type: 'span'
			_key: string
		}>
		style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
		listItem?: 'bullet' | 'number'
		markDefs?: Array<{
			href?: string
			_type: 'link'
			_key: string
		}>
		level?: number
		_type: 'block'
		_key: string
	}>
	coverImage?: {
		asset?: SanityImageAssetReference
		media?: unknown
		hotspot?: SanityImageHotspot
		crop?: SanityImageCrop
		_type: 'image'
	}
	featuredPosts?: Array<
		{
			_key: string
		} & BlogPostReference
	>
	featuredBooks?: Array<
		{
			_key: string
		} & BookReference
	>
}

export type Slug = {
	_type: 'slug'
	current?: string
	source?: string
}

export type Logo = {
	_id: string
	_type: 'logo'
	_createdAt: string
	_updatedAt: string
	_rev: string
	name?: string
	image?: {
		default?: {
			asset?: SanityImageAssetReference
			media?: unknown
			hotspot?: SanityImageHotspot
			crop?: SanityImageCrop
			_type: 'image'
		}
		light?: {
			asset?: SanityImageAssetReference
			media?: unknown
			hotspot?: SanityImageHotspot
			crop?: SanityImageCrop
			_type: 'image'
		}
		dark?: {
			asset?: SanityImageAssetReference
			media?: unknown
			hotspot?: SanityImageHotspot
			crop?: SanityImageCrop
			_type: 'image'
		}
	}
}

export type Redirect = {
	_id: string
	_type: 'redirect'
	_createdAt: string
	_updatedAt: string
	_rev: string
	source?: string
	destination?: Link
	permanent?: boolean
}

export type Announcement = {
	_id: string
	_type: 'announcement'
	_createdAt: string
	_updatedAt: string
	_rev: string
	content?: Array<{
		children?: Array<{
			marks?: Array<string>
			text?: string
			_type: 'span'
			_key: string
		}>
		style?: 'normal'
		listItem?: 'bullet' | 'number'
		markDefs?: Array<{
			href?: string
			_type: 'link'
			_key: string
		}>
		level?: number
		_type: 'block'
		_key: string
	}>
	cta?: Link
	start?: string
	end?: string
}

export type BlogCategory = {
	_id: string
	_type: 'blog.category'
	_createdAt: string
	_updatedAt: string
	_rev: string
	title?: string
	slug?: Slug
}

export type Book = {
	_id: string
	_type: 'book'
	_createdAt: string
	_updatedAt: string
	_rev: string
	title?: string
	defaultLink?: string
	countryLinks?: Array<{
		country?: string
		link?: string
		_key: string
	}>
	image?: {
		asset?: SanityImageAssetReference
		media?: unknown
		hotspot?: SanityImageHotspot
		crop?: SanityImageCrop
		_type: 'image'
	}
	authors?: Array<
		{
			_key: string
		} & PersonReference
	>
	active?: boolean
}

export type GlobalModule = {
	_id: string
	_type: 'global-module'
	_createdAt: string
	_updatedAt: string
	_rev: string
	path?: string
	excludePaths?: Array<string>
	before?: Array<
		| ({
				_key: string
		  } & AccordionList)
		| ({
				_key: string
		  } & BlogFrontpage)
		| ({
				_key: string
		  } & BlogList)
		| ({
				_key: string
		  } & BlogPostContent)
		| ({
				_key: string
		  } & Breadcrumbs)
		| ({
				_key: string
		  } & Callout)
		| ({
				_key: string
		  } & CardList)
		| ({
				_key: string
		  } & CreativeModule)
		| ({
				_key: string
		  } & CustomHtml)
		| ({
				_key: string
		  } & FlagList)
		| ({
				_key: string
		  } & Hero)
		| ({
				_key: string
		  } & HeroSaas)
		| ({
				_key: string
		  } & HeroSplit)
		| ({
				_key: string
		  } & LogoList)
		| ({
				_key: string
		  } & PersonList)
		| ({
				_key: string
		  } & PricingList)
		| ({
				_key: string
		  } & RichtextModule)
		| ({
				_key: string
		  } & ScheduleModule)
		| ({
				_key: string
		  } & SearchModule)
		| ({
				_key: string
		  } & StatList)
		| ({
				_key: string
		  } & StepList)
		| ({
				_key: string
		  } & TabbedContent)
		| ({
				_key: string
		  } & TestimonialList)
		| ({
				_key: string
		  } & TestimonialFeatured)
	>
	after?: Array<
		| ({
				_key: string
		  } & AccordionList)
		| ({
				_key: string
		  } & BlogFrontpage)
		| ({
				_key: string
		  } & BlogList)
		| ({
				_key: string
		  } & BlogPostContent)
		| ({
				_key: string
		  } & Breadcrumbs)
		| ({
				_key: string
		  } & Callout)
		| ({
				_key: string
		  } & CardList)
		| ({
				_key: string
		  } & CreativeModule)
		| ({
				_key: string
		  } & CustomHtml)
		| ({
				_key: string
		  } & FlagList)
		| ({
				_key: string
		  } & Hero)
		| ({
				_key: string
		  } & HeroSaas)
		| ({
				_key: string
		  } & HeroSplit)
		| ({
				_key: string
		  } & LogoList)
		| ({
				_key: string
		  } & PersonList)
		| ({
				_key: string
		  } & PricingList)
		| ({
				_key: string
		  } & RichtextModule)
		| ({
				_key: string
		  } & ScheduleModule)
		| ({
				_key: string
		  } & SearchModule)
		| ({
				_key: string
		  } & StatList)
		| ({
				_key: string
		  } & StepList)
		| ({
				_key: string
		  } & TabbedContent)
		| ({
				_key: string
		  } & TestimonialList)
		| ({
				_key: string
		  } & TestimonialFeatured)
	>
}

export type AnnouncementReference = {
	_ref: string
	_type: 'reference'
	_weak?: boolean
	[internalGroqTypeReferenceTo]?: 'announcement'
}

export type NavigationReference = {
	_ref: string
	_type: 'reference'
	_weak?: boolean
	[internalGroqTypeReferenceTo]?: 'navigation'
}

export type Site = {
	_id: string
	_type: 'site'
	_createdAt: string
	_updatedAt: string
	_rev: string
	title?: string
	blurb?: Array<{
		children?: Array<{
			marks?: Array<string>
			text?: string
			_type: 'span'
			_key: string
		}>
		style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
		listItem?: never
		markDefs?: Array<{
			href?: string
			_type: 'link'
			_key: string
		}>
		level?: number
		_type: 'block'
		_key: string
	}>
	logo?: {
		name?: string
		image?: {
			default?: {
				asset?: SanityImageAssetReference
				media?: unknown
				hotspot?: SanityImageHotspot
				crop?: SanityImageCrop
				_type: 'image'
			}
			light?: {
				asset?: SanityImageAssetReference
				media?: unknown
				hotspot?: SanityImageHotspot
				crop?: SanityImageCrop
				_type: 'image'
			}
			dark?: {
				asset?: SanityImageAssetReference
				media?: unknown
				hotspot?: SanityImageHotspot
				crop?: SanityImageCrop
				_type: 'image'
			}
		}
		_type: 'logo'
	}
	announcements?: Array<
		{
			_key: string
		} & AnnouncementReference
	>
	copyright?: Array<{
		children?: Array<{
			marks?: Array<string>
			text?: string
			_type: 'span'
			_key: string
		}>
		style?: 'normal'
		listItem?: never
		markDefs?: Array<{
			href?: string
			_type: 'link'
			_key: string
		}>
		level?: number
		_type: 'block'
		_key: string
	}>
	ctas?: Array<
		{
			_key: string
		} & Cta
	>
	headerMenu?: NavigationReference
	footerMenu?: NavigationReference
	social?: NavigationReference
}

export type Navigation = {
	_id: string
	_type: 'navigation'
	_createdAt: string
	_updatedAt: string
	_rev: string
	title?: string
	items?: Array<
		| ({
				_key: string
		  } & Link)
		| ({
				_key: string
		  } & LinkList)
	>
}

export type TranslationMetadata = {
	_id: string
	_type: 'translation.metadata'
	_createdAt: string
	_updatedAt: string
	_rev: string
	translations?: InternationalizedArrayReference
	schemaTypes?: Array<string>
}

export type InternationalizedArrayReference = Array<
	{
		_key: string
	} & InternationalizedArrayReferenceValue
>

export type InternationalizedArrayReferenceValue = {
	_type: 'internationalizedArrayReferenceValue'
	value?: PageReference | BlogPostReference
	language?: string
}

export type BlogPost = {
	_id: string
	_type: 'blog.post'
	_createdAt: string
	_updatedAt: string
	_rev: string
	body?: Array<
		| {
				children?: Array<{
					marks?: Array<string>
					text?: string
					_type: 'span'
					_key: string
				}>
				style?:
					'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
				listItem?: 'bullet' | 'number'
				markDefs?: Array<{
					href?: string
					_type: 'link'
					_key: string
				}>
				level?: number
				_type: 'block'
				_key: string
		  }
		| {
				asset?: SanityImageAssetReference
				media?: unknown
				hotspot?: SanityImageHotspot
				crop?: SanityImageCrop
				alt?: string
				loading?: 'lazy' | 'eager'
				caption?: string
				source?: string
				_type: 'image'
				_key: string
		  }
		| {
				tone?: 'note' | 'important' | 'tip' | 'warning' | 'caution'
				title?: string
				content?: Array<{
					children?: Array<{
						marks?: Array<string>
						text?: string
						_type: 'span'
						_key: string
					}>
					style?:
						'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
					listItem?: 'bullet' | 'number'
					markDefs?: Array<{
						href?: string
						_type: 'link'
						_key: string
					}>
					level?: number
					_type: 'block'
					_key: string
				}>
				_type: 'admonition'
				_key: string
		  }
		| ({
				_key: string
		  } & Code)
		| ({
				_key: string
		  } & CustomHtml)
	>
	categories?: Array<
		{
			_key: string
		} & BlogCategoryReference
	>
	youtubeEmbed?: {
		videoID?: string
	}
	authors?: Array<
		{
			_key: string
		} & PersonReference
	>
	publishDate?: string
	featured?: boolean
	metadata?: Metadata
	faq?: AccordionList
	language?: string
}

export type Page = {
	_id: string
	_type: 'page'
	_createdAt: string
	_updatedAt: string
	_rev: string
	title?: string
	modules?: Array<
		| ({
				_key: string
		  } & AccordionList)
		| ({
				_key: string
		  } & BlogFrontpage)
		| ({
				_key: string
		  } & BlogList)
		| ({
				_key: string
		  } & BlogPostContent)
		| ({
				_key: string
		  } & Breadcrumbs)
		| ({
				_key: string
		  } & Callout)
		| ({
				_key: string
		  } & CardList)
		| ({
				_key: string
		  } & CreativeModule)
		| ({
				_key: string
		  } & CustomHtml)
		| ({
				_key: string
		  } & FlagList)
		| ({
				_key: string
		  } & Hero)
		| ({
				_key: string
		  } & HeroSaas)
		| ({
				_key: string
		  } & HeroSplit)
		| ({
				_key: string
		  } & LogoList)
		| ({
				_key: string
		  } & PersonList)
		| ({
				_key: string
		  } & PricingList)
		| ({
				_key: string
		  } & RichtextModule)
		| ({
				_key: string
		  } & ScheduleModule)
		| ({
				_key: string
		  } & SearchModule)
		| ({
				_key: string
		  } & StatList)
		| ({
				_key: string
		  } & StepList)
		| ({
				_key: string
		  } & TabbedContent)
		| ({
				_key: string
		  } & TestimonialList)
		| ({
				_key: string
		  } & TestimonialFeatured)
	>
	markdown?: Code
	metadata?: Metadata
	language?: string
}

export type Code = {
	_type: 'code'
	language?: string
	filename?: string
	code?: string
	highlightedLines?: Array<number>
}

export type Reputation = {
	_id: string
	_type: 'reputation'
	_createdAt: string
	_updatedAt: string
	_rev: string
	title?: string
	subtitle?: string
	repo?: string
	showForks?: boolean
	limit?: number
	avatars?: Array<{
		asset?: SanityImageAssetReference
		media?: unknown
		hotspot?: SanityImageHotspot
		crop?: SanityImageCrop
		alt?: string
		_type: 'image'
		_key: string
	}>
}

export type SanityAssistInstructionTask = {
	_type: 'sanity.assist.instructionTask'
	path?: string
	instructionKey?: string
	started?: string
	updated?: string
	info?: string
}

export type SanityAssistTaskStatus = {
	_type: 'sanity.assist.task.status'
	tasks?: Array<
		{
			_key: string
		} & SanityAssistInstructionTask
	>
}

export type SanityAssistSchemaTypeAnnotations = {
	_type: 'sanity.assist.schemaType.annotations'
	title?: string
	fields?: Array<
		{
			_key: string
		} & SanityAssistSchemaTypeField
	>
}

export type SanityAssistOutputType = {
	_type: 'sanity.assist.output.type'
	type?: string
}

export type SanityAssistOutputField = {
	_type: 'sanity.assist.output.field'
	path?: string
}

export type AssistInstructionContextReference = {
	_ref: string
	_type: 'reference'
	_weak?: boolean
	[internalGroqTypeReferenceTo]?: 'assist.instruction.context'
}

export type SanityAssistInstructionContext = {
	_type: 'sanity.assist.instruction.context'
	reference?: AssistInstructionContextReference
}

export type AssistInstructionContext = {
	_id: string
	_type: 'assist.instruction.context'
	_createdAt: string
	_updatedAt: string
	_rev: string
	title?: string
	context?: Array<{
		children?: Array<{
			marks?: Array<string>
			text?: string
			_type: 'span'
			_key: string
		}>
		style?: 'normal'
		listItem?: never
		markDefs?: null
		level?: number
		_type: 'block'
		_key: string
	}>
}

export type SanityAssistInstructionUserInput = {
	_type: 'sanity.assist.instruction.userInput'
	message?: string
	description?: string
}

export type SanityAssistInstructionPrompt = Array<{
	children?: Array<
		| {
				marks?: Array<string>
				text?: string
				_type: 'span'
				_key: string
		  }
		| ({
				_key: string
		  } & SanityAssistInstructionFieldRef)
		| ({
				_key: string
		  } & SanityAssistInstructionContext)
		| ({
				_key: string
		  } & SanityAssistInstructionUserInput)
	>
	style?: 'normal'
	listItem?: never
	markDefs?: null
	level?: number
	_type: 'block'
	_key: string
}>

export type SanityAssistInstructionFieldRef = {
	_type: 'sanity.assist.instruction.fieldRef'
	path?: string
}

export type SanityAssistInstruction = {
	_type: 'sanity.assist.instruction'
	prompt?: SanityAssistInstructionPrompt
	icon?: string
	title?: string
	userId?: string
	createdById?: string
	output?: Array<
		| ({
				_key: string
		  } & SanityAssistOutputField)
		| ({
				_key: string
		  } & SanityAssistOutputType)
	>
}

export type SanityAssistSchemaTypeField = {
	_type: 'sanity.assist.schemaType.field'
	path?: string
	instructions?: Array<
		{
			_key: string
		} & SanityAssistInstruction
	>
}

export type MediaTag = {
	_id: string
	_type: 'media.tag'
	_createdAt: string
	_updatedAt: string
	_rev: string
	name?: Slug
}

export type SanityImagePaletteSwatch = {
	_type: 'sanity.imagePaletteSwatch'
	background?: string
	foreground?: string
	population?: number
	title?: string
}

export type SanityImagePalette = {
	_type: 'sanity.imagePalette'
	darkMuted?: SanityImagePaletteSwatch
	lightVibrant?: SanityImagePaletteSwatch
	darkVibrant?: SanityImagePaletteSwatch
	vibrant?: SanityImagePaletteSwatch
	dominant?: SanityImagePaletteSwatch
	lightMuted?: SanityImagePaletteSwatch
	muted?: SanityImagePaletteSwatch
}

export type SanityImageDimensions = {
	_type: 'sanity.imageDimensions'
	height?: number
	width?: number
	aspectRatio?: number
}

export type SanityImageMetadata = {
	_type: 'sanity.imageMetadata'
	location?: Geopoint
	dimensions?: SanityImageDimensions
	palette?: SanityImagePalette
	lqip?: string
	blurHash?: string
	thumbHash?: string
	hasAlpha?: boolean
	isOpaque?: boolean
}

export type SanityFileAsset = {
	_id: string
	_type: 'sanity.fileAsset'
	_createdAt: string
	_updatedAt: string
	_rev: string
	originalFilename?: string
	label?: string
	title?: string
	description?: string
	altText?: string
	sha1hash?: string
	extension?: string
	mimeType?: string
	size?: number
	assetId?: string
	uploadId?: string
	path?: string
	url?: string
	source?: SanityAssetSourceData
}

export type SanityAssetSourceData = {
	_type: 'sanity.assetSourceData'
	name?: string
	id?: string
	url?: string
}

export type SanityImageAsset = {
	_id: string
	_type: 'sanity.imageAsset'
	_createdAt: string
	_updatedAt: string
	_rev: string
	originalFilename?: string
	label?: string
	title?: string
	description?: string
	altText?: string
	sha1hash?: string
	extension?: string
	mimeType?: string
	size?: number
	assetId?: string
	uploadId?: string
	path?: string
	url?: string
	metadata?: SanityImageMetadata
	source?: SanityAssetSourceData
}

export type Geopoint = {
	_type: 'geopoint'
	lat?: number
	lng?: number
	alt?: number
}

export type AllSanitySchemaTypes =
	| SanityImageAssetReference
	| CardImage
	| ResponsiveImage
	| TestimonialReference
	| TestimonialList
	| TestimonialFeatured
	| TabbedContent
	| StepList
	| StatList
	| SearchModule
	| ScheduleModule
	| RichtextModule
	| PricingReference
	| PricingList
	| PersonReference
	| PersonList
	| LogoReference
	| LogoList
	| ReputationReference
	| HeroSplit
	| HeroSaas
	| Hero
	| FlagList
	| CustomHtml
	| CreativeModule
	| CardList
	| Callout
	| Breadcrumbs
	| BlogPostContent
	| BlogCategoryReference
	| BlogList
	| BlogFrontpage
	| AccordionList
	| ModuleOptions
	| Metadata
	| LinkList
	| PageReference
	| BlogPostReference
	| Link
	| Img
	| Icon
	| Cta
	| Testimonial
	| SanityImageCrop
	| SanityImageHotspot
	| Pricing
	| BookReference
	| Person
	| Slug
	| Logo
	| Redirect
	| Announcement
	| BlogCategory
	| Book
	| GlobalModule
	| AnnouncementReference
	| NavigationReference
	| Site
	| Navigation
	| TranslationMetadata
	| InternationalizedArrayReference
	| InternationalizedArrayReferenceValue
	| BlogPost
	| Page
	| Code
	| Reputation
	| SanityAssistInstructionTask
	| SanityAssistTaskStatus
	| SanityAssistSchemaTypeAnnotations
	| SanityAssistOutputType
	| SanityAssistOutputField
	| AssistInstructionContextReference
	| SanityAssistInstructionContext
	| AssistInstructionContext
	| SanityAssistInstructionUserInput
	| SanityAssistInstructionPrompt
	| SanityAssistInstructionFieldRef
	| SanityAssistInstruction
	| SanityAssistSchemaTypeField
	| MediaTag
	| SanityImagePaletteSwatch
	| SanityImagePalette
	| SanityImageDimensions
	| SanityImageMetadata
	| SanityFileAsset
	| SanityAssetSourceData
	| SanityImageAsset
	| Geopoint
