name: Weekly Newsletter Trigger

on:
  workflow_dispatch: {}
  schedule:
    - cron: '30 3 * * 1' # 9:00 AM IST is 3:30 AM UTC

jobs:
  trigger-newsletter:
    runs-on: ubuntu-latest
    steps:
      - name: Send GET request to newsletter API
        run: |
          curl -X GET "https://blog.abhimanyu-saharan.com/api/newsletter/send" \
            -H "Authorization: Bearer ${{ secrets.CRON_SECRET }}"
